export const translations = {
  en: {
    login: "Log in",
    signup: "Sign up",
    messages: "Messages",
    upcomingTrips: "Upcoming trips",
    allBookings: "All bookings",
    accountSettings: "Account settings",
    logout: "Log out",
    language: "Language & region",
    currency: "Currency",
    viewProfile: "View profile",
    // Landlord translations
    dashboard: "Dashboard",
    properties: "Properties",
    reservations: "Reservations",
    earnings: "Earnings",
  },
  fr: {
    login: "Connexion",
    signup: "S'inscrire",
    messages: "Messages",
    upcomingTrips: "Voyages à venir",
    allBookings: "Toutes les réservations",
    accountSettings: "Paramètres du compte",
    logout: "Déconnexion",
    language: "Langue et région",
    currency: "Devise",
    viewProfile: "Voir le profil",
    dashboard: "Tableau de bord",
    properties: "Propriétés",
    reservations: "Réservations",
    earnings: "Revenus",
  },
};
